Repository TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted, pull requests merged in 2024-04, with the labels that each got.

#368 [FEATURE] #87889 - Make backend URL configurable
  Documentation/Concepts/Index.rst
  Documentation/Localization.ru_RU/Concepts/Index.rst
Labels: changelog

#373 [TASK] Remove genindex and screenshots
  Documentation/Index.rst
  Documentation/genindex.rst
  Documentation/screenshots.json
Labels: backport 11.5, backport 12.4

#372 [TASK] Overhaul start page
  Documentation/Index.rst
Labels: backport 11.5, backport 12.4

#376 Overhaul TYPO3 Tutorial Getting Started
  Documentation/Index.rst
Labels: backport 12.4

#377 [BUGFIX] Resolve duplicate link anchors
  Documentation/Extensions/LegacyManagement.rst
  Documentation/Localization.ru_RU/Extensions/LegacyManagement.rst
Labels: backport 11.5, backport 12.4
