Repository TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted, pull requests merged in 2024-03, with the labels that each got.

#340 [TASK] Remove note about using RC for Doctrine DBAL v4
  Documentation/Installation/Install.rst
Labels: changelog

#342 [TASK] Split up deployment section
  Documentation/Installation/DeployTYPO3.rst
  Documentation/Installation/Deployer/Index.rst
  Documentation/Installation/Deployer/_deploy.php
  Documentation/Installation/Magallanes/Index.rst
  Documentation/Installation/Magallanes/_mage.yml
  Documentation/Installation/Surf/Index.rst
  Documentation/Installation/Surf/_MyDeployment.php
Labels: backport 12.4

#344 [TASK] Re-order "Installation" sub-sections
  Documentation/Installation/Index.rst
Labels: backport 11.5, backport 12.4

#347 [TASK] Move ReleaseIntegrity to a subsection of LegacyInstallation
  Documentation/Installation/Index.rst
  Documentation/Installation/LegacyInstallation.rst
Labels: backport 11.5, backport 12.4

#349 [TASK] Streamline "Release integrity" chapter
  Documentation/Installation/ReleaseIntegrity.rst
Labels: backport 12.4

#352 [TASK] Move "Production settings" to distinct section
  Documentation/Installation/DeployTYPO3.rst
  Documentation/Installation/EnvironmentConfiguration.rst
  Documentation/Installation/Index.rst
Labels: backport 12.4

#351 [TASK] Use text roles in "Release integrity" chapter
  Documentation/Installation/ReleaseIntegrity.rst
Labels: backport 12.4

#356 [TASK] Adjust heading levels in "Release integrity" chapter
  Documentation/Installation/ReleaseIntegrity.rst
Labels: backport 11.5, backport 12.4

#339 [TASK] Add Permissions Synchronization chapter to Permissions Management docs
  Documentation/PermissionsManagement/Index.rst
  Documentation/PermissionsManagement/PermissionsSynchronization/Index.rst
Labels: backport 11.5, backport 12.4

#357 [FEATURE] Add environment configuration section
  Documentation/Installation/EnvironmentConfiguration.rst
  Documentation/Installation/Environments/_additional-context.php
  Documentation/Installation/Environments/_additional-native.php
  Documentation/Installation/Environments/_additional.php
  Documentation/Installation/Environments/_dotenv-symfony.php
  Documentation/Installation/Environments/_dotenv-vlucas.php
  Documentation/Installation/Environments/_environment.php
  Documentation/Installation/Environments/_example.env
  Documentation/Installation/Index.rst
  Documentation/Installation/ProductionSettings.rst
Labels: backport 12.4

#361 [TASK] Adjust .editorconfig for Makefile indentation
  .editorconfig
Labels: backport 11.5, backport 12.4

#364 [TASK] Remove deprecation
  Documentation/Installation/Install.rst
  Documentation/Installation/TutorialDdev.rst
  Documentation/Localization.ru_RU/Installation/Install.rst
  Documentation/Localization.ru_RU/Installation/TutorialDdev.rst
Labels: backport 11.5, backport 12.4
