Repository TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted, pull requests merged in 2024-11, with the labels that each got.

#535 [Task] Description about how to find extensions and renaming management
  Documentation/Extensions/HowToFindExtensions.rst
  Documentation/Extensions/Index.rst
  Documentation/Extensions/InstallingExtensions.rst
Labels: backport 12.4, backport 13.4

#534 Adding next steps in first project setup
  Documentation/FirstProject/CreateSitePackage.rst
  Documentation/FirstProject/Index.rst
Labels: backport 12.4, backport 13.4

#536 [Task] List of recommended extensions
  Documentation/Extensions/Index.rst
  Documentation/Extensions/RecommendedExtensions.rst
Labels: backport 12.4, backport 13.4

#547 [BUGFIX] Fix Card Link in Trouble shooting
  Documentation/Troubleshooting/Index.rst
Labels: backport 12.4, backport 13.4

#545 [TASK] Improve Extension concept definitions
  Documentation/Concepts/Extensions/Index.rst
  Documentation/Images/Illustrations/extensions.png
Labels: backport 12.4, backport 13.4

#556 [TASK] Update Screenshots for backend overview
  Documentation/Concepts/Backend/GeneralBackendStructure/Index.rst
  Documentation/Concepts/Backend/GeneralBackendStructure/PageTree/Index.rst
  Documentation/Concepts/Backend/Index.rst
  Documentation/Images/AutomaticScreenshots/BackendOverview/BackendAreasOverview.png
  Documentation/Images/AutomaticScreenshots/BackendOverview/BackendAreasOverview.rst.txt
  Documentation/Images/ManualScreenshots/Backend/BackendAreasOverviewShort.png
Labels: backport 12.4, backport 13.4

#565 Add anchor
  Documentation/Concepts/TypoScript/Index.rst
Labels: backport 12.4, backport 13.4

#560 [TASK] Write information on List module for Developers and Integrators
  Documentation/Concepts/Backend/ListModule/AdvancedClipboard/Index.rst
  Documentation/Concepts/Backend/ListModule/Clipboard/Index.rst
  Documentation/Concepts/Backend/ListModule/Index.rst
  Documentation/Concepts/Backend/ListModule/MassEditing/Index.rst
  Documentation/Concepts/Backend/ListModule/UsingEffectively/Index.rst
  Documentation/Images/AutomaticScreenshots/ListModule/ActivateClipboardPad.png
  Documentation/Images/AutomaticScreenshots/ListModule/ActivateClipboardPad.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/ClipboardWarning.png
  Documentation/Images/AutomaticScreenshots/ListModule/ClipboardWarning.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/ClipboardWithMultipleItems.png
  Documentation/Images/AutomaticScreenshots/ListModule/ClipboardWithMultipleItems.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/CopyToClipboard.png
  Documentation/Images/AutomaticScreenshots/ListModule/CopyToClipboard.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/ListModule.png
  Documentation/Images/AutomaticScreenshots/ListModule/ListModule.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/ListModuleContentArea.png
  Documentation/Images/AutomaticScreenshots/ListModule/ListModuleContentArea.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditHeader.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditHeader.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditHeaderButton.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditHeaderButton.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditMultipleFieldsButton.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditMultipleFieldsButton.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditingEnabled.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassEditingEnabled.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassMultipleFields.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/MassMultipleFields.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/RecordListWithAdditionalFields.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/RecordListWithAdditionalFields.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/SelectiveEditing.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/SelectiveEditing.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/ShowColumnsButton.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/ShowColumnsButton.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/ShowColumnsModal.png
  Documentation/Images/AutomaticScreenshots/ListModule/MassEdit/ShowColumnsModal.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/MovedContentEmpyClipboard.png
  Documentation/Images/AutomaticScreenshots/ListModule/MovedContentEmpyClipboard.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/PasteClipboardContent.png
  Documentation/Images/AutomaticScreenshots/ListModule/PasteClipboardContent.rst.txt
  Documentation/Images/AutomaticScreenshots/ListModule/SimpleClipboard.png
  Documentation/Images/AutomaticScreenshots/ListModule/SimpleClipboard.rst.txt
Labels: backport 12.4, backport 13.4

#561 [TASK] Write information on Page module for Developers and Integrators
  Documentation/Concepts/Backend/PageModule/Index.rst
  Documentation/Images/AutomaticScreenshots/PageModule/ContentElementBackend.png
  Documentation/Images/AutomaticScreenshots/PageModule/ContentElementBackend.rst.txt
  Documentation/Images/AutomaticScreenshots/PageModule/TextInColumnsBackend.png
  Documentation/Images/AutomaticScreenshots/PageModule/TextInColumnsBackend.rst.txt
  Documentation/Images/AutomaticScreenshots/PageTree/PageContent1.png
  Documentation/Images/AutomaticScreenshots/PageTree/PageContent1.rst.txt
  Documentation/Images/ManualScreenshots/Backend/NewPageContentWizard.png
  Documentation/Images/ManualScreenshots/Frontend/TextInColumnsFrontend.png
Labels: backport 12.4, backport 13.4

#562 [TASK] Update System modules section
  Documentation/Concepts/Backend/SystemModules/Index.rst
  Documentation/Images/AutomaticScreenshots/Modules/DbCheckModule.png
  Documentation/Images/AutomaticScreenshots/Modules/DbCheckModule.rst.txt
  Documentation/Images/AutomaticScreenshots/Modules/LogModule.png
  Documentation/Images/AutomaticScreenshots/Modules/LogModule.rst.txt
  Documentation/Images/AutomaticScreenshots/Modules/ReportsModule.png
  Documentation/Images/AutomaticScreenshots/Modules/ReportsModule.rst.txt
  Documentation/Images/AutomaticScreenshots/Modules/System.png
  Documentation/Images/AutomaticScreenshots/Modules/System.rst.txt
  Documentation/Images/AutomaticScreenshots/Modules/TemplateModule.png
  Documentation/Images/AutomaticScreenshots/Modules/TemplateModule.rst.txt
  Documentation/Installation/Install.rst
Labels: backport 12.4, backport 13.4

#563 [TASK] Create section describing all Admin Tools
  Documentation/Concepts/Backend/AdminTools/ContentSecurityPolicy.rst
  Documentation/Concepts/Backend/AdminTools/Environment.rst
  Documentation/Concepts/Backend/AdminTools/Extensions.rst
  Documentation/Concepts/Backend/AdminTools/Index.rst
  Documentation/Concepts/Backend/AdminTools/Maintenance.rst
  Documentation/Concepts/Backend/AdminTools/Settings.rst
  Documentation/Concepts/Backend/AdminTools/Upgrade.rst
  Documentation/Concepts/Backend/Index.rst
  Documentation/Images/ManualScreenshots/AdminTools/InstallToolHash.png
Labels: backport 12.4, backport 13.4

#564 [TASK] Update Filelist section
  Documentation/Concepts/Backend/FileModule/Index.rst
  Documentation/Images/AutomaticScreenshots/FilelistModule/FileClipboard.png
  Documentation/Images/AutomaticScreenshots/FilelistModule/FileClipboard.rst.txt
  Documentation/Images/AutomaticScreenshots/FilelistModule/FileUpload.png
  Documentation/Images/AutomaticScreenshots/FilelistModule/FileUpload.rst.txt
  Documentation/Images/AutomaticScreenshots/FilelistModule/FilelistModule.png
  Documentation/Images/AutomaticScreenshots/FilelistModule/FilelistModule.rst.txt
Labels: backport 12.4, backport 13.4

#568 [TASK] Update Site management section
  Documentation/Concepts/Backend/Index.rst
  Documentation/Concepts/Backend/SiteManagement/Index.rst
  Documentation/Concepts/Backend/SiteManagement/PageTSconfig.rst
  Documentation/Concepts/Backend/SiteManagement/Redirects.rst
  Documentation/Concepts/Backend/SiteManagement/Settings.rst
  Documentation/Concepts/Backend/SiteManagement/Sites.rst
  Documentation/Concepts/Backend/SiteManagement/TypoScript.rst
  Documentation/Images/ManualScreenshots/Modules/TypoScript.png
Labels: backport-required, backport 13.4

#580 [TASK] Add hint for test phase
  Documentation/Includes.rst.txt
Labels: backport 12.4, backport 13.4

#584 Update Web Server Type
  Documentation/Installation/Install.rst
Labels: backport 13.4

#588 [TASK] Adjust links to TSconfig reference
  Documentation/Concepts/Backend/ListModule/Index.rst
  Documentation/Concepts/Backend/PageModule/Index.rst
  Documentation/Concepts/Backend/SiteManagement/PageTSconfig.rst
  Documentation/FirstProject/Settings.rst
Labels: backport 12.4, backport 13.4
