Repository TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted, pull requests merged in 2024-10, with the labels that each got.

#415 [TASK] Use --minimal-test CLI option for documentation tests
  .github/workflows/test-documentation.yml
  Makefile
Labels: backport 11.5, backport 12.4

#417 List answers for typo setup questions as to be used with DDEV
  Documentation/Installation/TutorialDdev.rst
Labels: backport 12.4

#419 Suggest to start with PHP 8.3
  Documentation/Installation/TutorialDdev.rst
Labels: backport 12.4

#420 [FEATURE] Add information on creating a site
  Documentation/Index.rst
  Documentation/SiteManagement/Index.rst
  Documentation/SiteManagement/NewSite.png
  Documentation/SiteManagement/NewSitePage1.png
  Documentation/SiteManagement/NewSitePageLanguage.png
  Documentation/SiteManagement/_config.yaml
Labels: backport-required

#423 Minor language fixes
  Documentation/Installation/Install.rst
Labels: backport 12.4

#422 [FEATURE] Add basic TypoScript examples
  Documentation/Index.rst
  Documentation/TypoScript/ActiveTypoScript.png
  Documentation/TypoScript/Index.rst
  Documentation/TypoScript/_minimal-output.html
  Documentation/TypoScript/_minimal.typoscript
  Documentation/TypoScript/_page-title.typoscript
  Documentation/TypoScript/_page-title_reverse.typoscript
  Documentation/TypoScript/_stdwrap.typoscript
  Documentation/TypoScript/_stdwrap_direct.typoscript
Labels: backport-required

#427 [FEATURE] Document where to put media and assets.
  Documentation/Assets/Index.rst
  Documentation/Index.rst
Labels: backport 12.4

#445 [TASK] Move system requirements into installation
  Documentation/Index.rst
  Documentation/Installation/Index.rst
  Documentation/Installation/SystemRequirements/Apache.rst.txt
  Documentation/Installation/SystemRequirements/Database.rst.txt
  Documentation/Installation/SystemRequirements/IIS.rst.txt
  Documentation/Installation/SystemRequirements/Index.rst
  Documentation/Installation/SystemRequirements/NGINX.rst.txt
  Documentation/Installation/SystemRequirements/PHP.rst.txt
Labels: backport 12.4

#442 [TASK] Move Backend user related pages into UserMangement
  Documentation/Setup/Index.rst
  Documentation/UserManagement/BackendLanguages.rst
  Documentation/UserManagement/BackendUsers.rst
  Documentation/UserManagement/Index.rst
Labels: backport 12.4

#453 [TASK] Rename Setup in "First project setup"
  Documentation/FirstProject/Index.rst
  Documentation/FirstProject/Settings.rst
  Documentation/FirstProject/SiteRecords.rst
  Documentation/Index.rst
  Documentation/Installation/Install.rst
Labels: backport 12.4

#456 Update Management.rst
  Documentation/Extensions/Management.rst
Labels: backport 12.4

#457 [TASK] Move the Fluid introduction information from the site package …
  Documentation/Concepts/Fluid/Index.rst
  Documentation/Concepts/Index.rst
Labels: backport 12.4

#459 Add missing anchor
  Documentation/FirstProject/Index.rst
Labels: backport 13.4

#462 [TASK] Document "How to create a root page"
  Documentation/FirstProject/CreateRootPage.rst
  Documentation/FirstProject/Index.rst
  Documentation/Images/ManualScreenshots/CreateRootPage/CreateNewPage.png
  Documentation/Images/ManualScreenshots/CreateRootPage/PageMenu.png
  Documentation/Images/ManualScreenshots/CreateRootPage/PageModule.png
  Documentation/Images/ManualScreenshots/CreateRootPage/SetRootPage.png
Labels: backport 12.4, backport 13.4

#474 [TASK] Move the assets into TYPO3 concepts
  Documentation/Concepts/Assets/Index.rst
  Documentation/Concepts/Index.rst
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4

#477 [TASK] Move tuning TYPO3 chapter to TYPO3 Explained
  Documentation/Installation/Index.rst
  Documentation/Installation/TuneTYPO3.rst
Labels: backport 12.4, backport 13.4

#485 Remove reference to composer/legacy in installation
  Documentation/FirstProject/IntroductionPackage/Index.rst
Labels: backport 12.4, backport 13.4

#483 [TASK]: Fix link to TYPO3 Concepts
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4

#482 feat(TASK): Link to "how to create a root page"
  Documentation/FirstProject/SiteManagement/Index.rst
Labels: backport 12.4, backport 13.4

#478 [TASK] Description about TCA
  Documentation/Concepts/Index.rst
  Documentation/Concepts/TCA/Index.rst
Labels: backport 12.4, backport 13.4

#496 [TASK] Move legacy installation info to TYPO3 Explained
  Documentation/Installation/Index.rst
  Documentation/Installation/LegacyInstallation.rst
  Documentation/Installation/ReleaseIntegrity.rst
Labels: backport 12.4, backport 13.4

#501 [TASK] Move automatic deployment to TYPO3 explained
  Documentation/Installation/DeployTYPO3.rst
  Documentation/Installation/Deployer/Index.rst
  Documentation/Installation/Deployer/_deploy.php
  Documentation/Installation/Magallanes/Index.rst
  Documentation/Installation/Magallanes/_mage.yml
  Documentation/Installation/Surf/Index.rst
  Documentation/Installation/Surf/_MyDeployment.php
Labels: backport 12.4

#500 [TASK] Move automatic System requirements to TYPO3 explained
  Documentation/Installation/SystemRequirements/Apache.rst.txt
  Documentation/Installation/SystemRequirements/Database.rst.txt
  Documentation/Installation/SystemRequirements/IIS.rst.txt
  Documentation/Installation/SystemRequirements/Index.rst
  Documentation/Installation/SystemRequirements/NGINX.rst.txt
  Documentation/Installation/SystemRequirements/PHP.rst.txt
Labels: backport 12.4, backport 13.4

#504 [TASK] Condense enviroment config
  Documentation/Installation/EnvironmentConfiguration.rst
  Documentation/Installation/Environments/_additional-context.php
  Documentation/Installation/Environments/_additional-native.php
  Documentation/Installation/Environments/_additional.php
  Documentation/Installation/Environments/_dotenv-symfony.php
  Documentation/Installation/Environments/_dotenv-vlucas.php
  Documentation/Installation/Environments/_environment.php
  Documentation/Installation/Environments/_example.env
  Documentation/Installation/Index.rst
  Documentation/Installation/ProductionSettings.rst
Labels: backport 12.4, backport 13.4

#507 [TASK] Condense Installation Chapters
  Documentation/Installation/Index.rst
  Documentation/Installation/Install.rst
  Documentation/Installation/TutorialDdev.rst
Labels: backport 12.4, backport 13.4

#509 [TASK] Move troubleshooting to TYPO3 explained
  Documentation/Troubleshooting/Database.rst
  Documentation/Troubleshooting/Index.rst
  Documentation/Troubleshooting/PHP.rst
  Documentation/Troubleshooting/SystemModules.rst
  Documentation/Troubleshooting/TYPO3.rst
  Documentation/Troubleshooting/WebServer.rst
Labels: backport 12.4, backport 13.4

#511 [TASK] Write a chapter on backend login trouble shooting
  Documentation/Troubleshooting/BackendLogin.rst
  Documentation/Troubleshooting/Index.rst
Labels: backport 12.4, backport 13.4

#515 [TASK]: Moved extensions to seperat file
  Documentation/Concepts/Extensions/Index.rst
  Documentation/Concepts/Index.rst
Labels: backport 12.4, backport 13.4

#521 [TASK] Introduce runTest.sh for unified testing.
  .github/workflows/tests.yml
  .gitignore
  Build/.gitignore
  Build/.php-cs-fixer.dist.php
  Build/Scripts/runTests.sh
  Build/Scripts/validateRstFiles.php
  Makefile
  composer.json
Labels: backport-required, backport 13.4

#520 [TASK] Write information on application context
  Documentation/Installation/ApplicationContext.rst
  Documentation/Installation/EnvironmentConfiguration.rst
  Documentation/Installation/Index.rst
  Documentation/Installation/_ApplicationContext/ApplicationContextInformation.png
  Documentation/Installation/_ApplicationContext/_additional-2.php
  Documentation/Installation/_ApplicationContext/_additional.php
  Documentation/Installation/_ApplicationContext/_credentials.php
  Documentation/Installation/_ApplicationContext/_docker-compose.context.yaml
Labels: backport 12.4, backport 13.4

#519 Description about Cache and how to clear cache
  Documentation/Concepts/Cache/Index.rst
  Documentation/Concepts/Index.rst
  Documentation/Images/ManualScreenshots/ClearCache/Toolbar.png
Labels: backport 12.4, backport 13.4

#528 Description on how to create own extension
  Documentation/Extensions/CreateOwnExtension.rst
  Documentation/Extensions/Index.rst
Labels: backport 12.4, backport 13.4

#531 Add description about project structure
  Documentation/Concepts/Index.rst
  Documentation/Concepts/ProjectStructure/Index.rst
Labels: backport 12.4, backport 13.4
